# Generated by Django 5.0.6 on 2024-05-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employeeID', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dateOfBirth', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.employee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo', models.IntegerField(default=1)),
                ('dev', models.IntegerField(default=2)),
                ('hr', models.IntegerField(default=3)),
                ('supervisor', models.IntegerField(default=4)),
                ('regularEmployee', models.IntegerField(default=5)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
