# Generated by Django 5.0.6 on 2024-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_employee_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Positions',
        ),
    ]
