# Generated by Django 5.0.6 on 2024-05-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo', models.IntegerField(default=1)),
                ('dev', models.IntegerField(default=2)),
                ('hr', models.IntegerField(default=3)),
                ('supervisor', models.IntegerField(default=4)),
                ('regularEmployee', models.IntegerField(default=5)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
    ]
